# Setup
title:               Lab
tagline:             "WNLO Hui Gao's Team"
description:         ''
url:                 https://optical-engineering.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hui Gao
  url:               https://optical-engineering.github.io
  email:             sena86088@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
